/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddJobItemForm: typeof import('./src/components/job-item-form/AddJobItemForm.vue')['default']
    AddJobOrderHeader: typeof import('./src/components/AddJobOrderHeader.vue')['default']
    ClaimForm: typeof import('./src/components/ClaimForm.vue')['default']
    ClaimTable: typeof import('./src/components/ClaimTable.vue')['default']
    CustomerSearch: typeof import('./src/components/CustomerSearch.vue')['default']
    CustomerSelector: typeof import('./src/components/CustomerSelector.vue')['default']
    EditJobItemForm: typeof import('./src/components/job-item-form/EditJobItemForm.vue')['default']
    FlagDetails: typeof import('./src/components/FlagDetails.vue')['default']
    FlagHeader: typeof import('./src/components/FlagHeader.vue')['default']
    JobItemExtrasFields: typeof import('./src/components/job-item-form/JobItemExtrasFields.vue')['default']
    JobItemPriceAdjustFields: typeof import('./src/components/job-item-form/JobItemPriceAdjustFields.vue')['default']
    JobItemPricingBreakdown: typeof import('./src/components/job-item-form/JobItemPricingBreakdown.vue')['default']
    JobItemServiceFields: typeof import('./src/components/job-item-form/JobItemServiceFields.vue')['default']
    JobItemTable: typeof import('./src/components/JobItemTable.vue')['default']
    JobItemWorkflowFields: typeof import('./src/components/job-item-form/JobItemWorkflowFields.vue')['default']
    JobOrderFooter: typeof import('./src/components/JobOrderFooter.vue')['default']
    JobOrderList: typeof import('./src/components/JobOrderList.vue')['default']
    JobOrderTable: typeof import('./src/components/JobOrderTable.vue')['default']
    MatchesList: typeof import('./src/components/MatchesList.vue')['default']
    MiscSaleForm: typeof import('./src/components/MiscSaleForm.vue')['default']
    NJobItemTable: typeof import('./src/components/nJobItemTable.vue')['default']
    OJobItemForm: typeof import('./src/components/oJobItemForm.vue')['default']
    OJobItemTable: typeof import('./src/components/oJobItemTable.vue')['default']
    OPaymentTable: typeof import('./src/components/oPaymentTable.vue')['default']
    OrderInfoInput: typeof import('./src/components/OrderInfoInput.vue')['default']
    OrderSummary: typeof import('./src/components/OrderSummary.vue')['default']
    PaymentDetails: typeof import('./src/components/PaymentDetails.vue')['default']
    PaymentForm: typeof import('./src/components/PaymentForm.vue')['default']
    PaymentsTable: typeof import(./src/components/oPaymentTable.vue/index.jsue')['default']
    PaymentTable: typeof import('./src/components/PaymentTable.vue')['default']
    ResolvePayment: typeof import('./src/components/ResolvePayment.vue')['default']
    ResolvePaymentSection: typeof import('./src/components/ResolvePaymentSection.vue')['default']
    ReviewHeader: typeof import('./src/components/ReviewHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UBreadcrumb: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCalendar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue')['default']
    UDashboardGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputDate: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue')['default']
    UInputMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UMain: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPagination: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USidebar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Sidebar.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
