"""add misc sale audit fields

Revision ID: 13188f512e61
Revises: 9f17dd03853e
Create Date: 2026-10-08 20:01:48.557428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13188f512e61'
down_revision: Union[str, Sequence[str], None] = '9f17dd03853e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('misc_sales', sa.Column('created_by_id', sa.Uuid(), nullable=False))
    op.add_column('misc_sales', sa.Column('updated_by_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_misc_sales_created_by_id'), 'misc_sales', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_misc_sales_updated_by_id'), 'misc_sales', ['updated_by_id'], unique=False)
    op.create_foreign_key(
        "fk_misc_sales_created_by_id_users",
        "misc_sales",
        "users",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_misc_sales_updated_by_id_users",
        "misc_sales",
        "users",
        ["updated_by_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "fk_misc_sales_updated_by_id_users",
        "misc_sales",
        type_="foreignkey",
    )
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "fk_misc_sales_created_by_id_users",
        "misc_sales",
        type_="foreignkey",
    )
    op.drop_index(op.f('ix_misc_sales_updated_by_id'), table_name='misc_sales')
    op.drop_index(op.f('ix_misc_sales_created_by_id'), table_name='misc_sales')
    op.drop_column('misc_sales', 'updated_by_id')
    op.drop_column('misc_sales', 'created_by_id')
    # ### end Alembic commands ###
